package {{ package }};

import com.dylibso.chicory.runtime.HostFunction;
import com.dylibso.chicory.runtime.Instance;
import com.dylibso.chicory.runtime.Memory;
import com.dylibso.chicory.wasm.types.ValueType;
{% if has_async -%}
import com.hubspot.boomslang.AsyncHostRegistry;
{% endif -%}
import com.hubspot.boomslang.BoomslangExtension;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
{% if has_async -%}
import java.util.concurrent.CompletionStage;
{% endif -%}
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** Generated by boomslang-hostgen. Do not edit by hand. */
public final class {{ class_name }} {

  private static final Logger LOG = LoggerFactory.getLogger(
    {{ class_name }}.class
  );
  private static final String EXTENSION_NAME = "{{ extension_name }}";
  private static final String MODULE = "{{ wasm_module }}";

  private {{ class_name }}() {}

{% for function in functions %}
  @FunctionalInterface
  public interface {{ function.handler_type }} {
    {{ function.return_type }} handle({{ function.interface_params }});
  }

{% endfor %}
  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder {

{% for function in functions %}
    private {{ function.handler_type }} {{ function.field }};
{% endfor %}
{% if has_async -%}
    private AsyncHostRegistry asyncRegistry;
{% endif %}
{% for function in functions %}

    public Builder {{ function.with_method }}({{ function.handler_type }} handler) {
      this.{{ function.field }} = handler;
      return this;
    }
{% endfor %}

{% if has_async -%}
    public Builder withAsyncRegistry(AsyncHostRegistry asyncRegistry) {
      this.asyncRegistry = asyncRegistry;
      return this;
    }

{% endif %}
    /** Builds all WASM imports for this extension. Missing handlers fail when invoked. */
    public HostFunction[] build() {
      List<HostFunction> functions = new ArrayList<>();
{% for function in functions %}
      functions.add(create{{ function.upper_name }}Function());
{% endfor %}
      return functions.toArray(new HostFunction[0]);
    }

    public BoomslangExtension buildExtension() {
      HostFunction[] hostFunctions = build();
      return new BoomslangExtension() {
        @Override
        public String name() {
          return EXTENSION_NAME;
        }

        @Override
        public HostFunction[] hostFunctions() {
          return hostFunctions.clone();
        }
      };
    }

    private IllegalStateException missingHandler(String functionName) {
      return new IllegalStateException(
        "No handler registered for host function " + MODULE + "::" + functionName
      );
    }

{% for function in functions %}
    private HostFunction create{{ function.upper_name }}Function() {
      return new HostFunction(
        MODULE,
        "{{ function.name }}",
        {{ function.wasm_params }},
        {{ function.wasm_returns }},
        (Instance instance, long... wasmArgs) -> {
{% if function.needs_memory %}          Memory memory = instance.memory();
{% endif %}{{ function.param_reads }}
          try {
            if ({{ function.field }} == null) {
              throw missingHandler("{{ function.name }}");
            }
{{ function.return_handling }}
          } catch (RuntimeException e) {
            LOG.error("Host function {}::{{ function.name }} failed", MODULE, e);
{{ function.error_handling }}
          }
        }
      );
    }

{% endfor %}
  }
}
